### ISSUE TITLE
Figma Description

### ISSUE THREAD

**Issue by cyrillicw** [DecentralizedPrimates/DecentralizedTracker#3]
Describe the features of Figma and consider the possibility of its application for the development UI of our app 
https://github.com/DecentralizedPrimates/DecentralizedTracker/wiki/Figma-description

**Comment by kirillbond** [comment]
https://www.figma.com/file/VOqV3p1BUqasFYTDmouPIz/Decentralized-Tracker?node-id=1%3A2

**Comment by kirillbond** [comment]
https://github.com/DecentralizedPrimates/DecentralizedTracker/wiki/Figma-descreption

**Comment by cyrillicw** [comment]
In fact, the given information looks like promotional products. The information WHAT is Figma is not given. The features and services that are provided to the Developer are not described.

**Comment by cyrillicw** [comment]
Some comparison with Sketch is given but I do not know what is Sketch - it is not described in the paper

**Comment by kirillbond** [comment]
Figma is a web-based graphics editing and user interface design app. You can use it to do all kinds of graphic design work from wireframing websites, designing mobile app interfaces, prototyping designs, crafting social media posts, and everything in between. Figma is different from other graphics editing tools.

so fit?

**Comment by cyrillicw** [comment]
All terms used in your page that are not widely known MUST be explained. The text that you have written down in the comment is OK but possibly it requires expanding. Look at your text and say whether a reader that does know anything about Figma can understand the opportunities it provides after reading your page
